-- FUNÇÕES DE DATA E HORA: aula 19 do ultrabook:
-- CURRENT_DATE = Função que retorna a data atual no formato aaaa-mm-dd:
SELECT CURRENT_DATE AS "Data Atual";

-- CURRENT_TIME = Função que retorna a hora atual - hora completa:
SELECT CURRENT_TIME AS "Hora Atual";

-- CALCULAR DATA FUTURA:
SELECT CURRENT_DATE + INTERVAL '3 DAY' AS "DATA DE VENCIMENTO"; 
SELECT CURRENT_DATE + INTERVAL '1 MONTH' AS "DATA DE VENCIMENTO"; 
SELECT CURRENT_DATE + INTERVAL '2 YEAR' AS "DATA DE VENCIMENTO"; 

-- CALCULAR PASSADA:
SELECT CURRENT_DATE - INTERVAL '3 DAY' AS "DATA PASSADA"; 
SELECT CURRENT_DATE - INTERVAL '1 MONTH' AS "DATA PASSADA"; 
SELECT CURRENT_DATE - INTERVAL '2 YEAR' AS "DATA PASSADA"; 

-- DIFERENÇA ENTRE DATAS:
-- EM ANOS:
SELECT DATE_PART('YEAR', '2019-01-01'::date) - DATE_PART('YEAR', '2011-10-02'::date) AS Em_anos;

-- EM MESES:
SELECT (DATE_PART('YEAR', '2019-01-01'::date) - DATE_PART('YEAR', '2011-10-02'::date)) * 12 +
	(DATE_PART('month', '2019-01-01'::date) - DATE_PART('month', '2011-10-02'::date)) AS Em_meses;
	
-- EM SEMANAS:
SELECT TRUNC (DATE_PART('day', '2019-01-01'::timestamp - '2011-12-22'::timestamp)/7) AS semanas;

-- EM DIAS:
SELECT TRUNC (DATE_PART('day', '2019-01-01'::timestamp - '2011-12-22'::timestamp)) AS dias;
SELECT DATE_PART('day', '2019-01-01'::timestamp - '2011-12-22'::timestamp) AS dias;

-- EM HORAS:
SELECT DATE_PART('day', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp)* 24 +
		DATE_PART('hour', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp) AS horas;

-- EM MINUTOS:
SELECT DATE_PART('day', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp)* 24 +
		DATE_PART('hour', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp) * 60 +
		DATE_PART('minutes', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp) AS minutos;

-- EM SEGUNDOS:
SELECT ((DATE_PART('day', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp)* 24 +
		DATE_PART('hour', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp)) * 60 +
		DATE_PART('minutes', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp)) * 60 +
		DATE_PART('second', '2019-01-01 11:55'::timestamp - '2019-01-01 09:55'::timestamp) AS em_segundos;

-- FORMATANDO DATAS NO POSTGRESQL:
SELECT TO_CHAR(CURRENT_DATE, 'dd/mm/YYYY') AS data_atual; 
SELECT TO_CHAR(CURRENT_DATE, 'mm/dd/YYYY') AS data_atual;
			   
SELECT TO_CHAR(NOW(), 'dd/mm/YYYY HH24:MM:SS') AS data_e_hora_atual;	
SELECT TO_CHAR(NOW(), 'dd/mm/YYYY HH12:MM:SS') AS data_e_hora_atual;

-- DAYNAME PostgreSQL:

-- COM INICIAL MAIÚSCULA:
-- EM INGLÊS:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'Day') AS dias_da_semana;
-- EM PORTUGUÊS:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'TMDay') AS dias_da_semana;

-- COM TUDO MAIÚSCULA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'DAY') AS dias_da_semana;

-- COM INICIAL MINÚSCULA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'day') AS dias_da_semana;

-- COM SHORT MAIÚSCULA: ABREVIATURA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'Dy') AS dias_da_semana;

-- COM SHORT MiNÚSCULA: ABREVIATURA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'dy') AS dias_da_semana;

-- MONTHNAME PostgreSQL:

-- COM INICIAL MAIÚSCULA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'Month') AS mês;

-- COM TUDO MAIÚSCULA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'MONTH') AS mês;

-- COM INICIAL MINÚSCULA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'month') AS mês;

-- COM SHORT MAIÚSCULA: ABREVIATURA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'Mon') AS mês;

-- COM SHORT MiNÚSCULA: ABREVIATURA:
SELECT TO_CHAR(CURRENT_TIMESTAMP, 'mon') AS mês;

-- para verificar a configuração da localização data-hora:
SHOW lc_time;

-- para alterar:
SET lc_time='en_US.UFT8';
SET lc_time='Portuguese_Brazil.1252';

-- EXTRAINDO PARTE DE UMA DATA:
SELECT EXTRACT (MONTH FROM CURRENT_TIMESTAMP) AS numero_mes;
SELECT EXTRACT (DAY FROM CURRENT_TIMESTAMP) AS numero_DIA;
SELECT EXTRACT (YEAR FROM CURRENT_TIMESTAMP) AS ANO;
SELECT EXTRACT (WEEK FROM CURRENT_TIMESTAMP) AS numero_SEMANA;
SELECT EXTRACT (HOUR FROM CURRENT_TIMESTAMP) AS HORA;
SELECT EXTRACT (MINUTE FROM CURRENT_TIMESTAMP) AS minutos;
SELECT EXTRACT (SECOND FROM CURRENT_TIMESTAMP) AS SEGUNDOS;
SELECT EXTRACT (MILLISECOND FROM CURRENT_TIMESTAMP) AS MILLISEGUNDOS;

-- CONVERTENDO DE SEGUNDO PARA HORA:
SELECT TO_CHAR((2000 || 'second')::interval, 'HH24:MM:SS') AS tempo_total;
SELECT TO_CHAR((72000 || 'second')::interval, 'HH24:MM:SS') AS tempo_total;
SELECT TO_CHAR((7200 || 'minute')::interval, 'HH24:MM:SS') AS tempo_total;

SELECT EXTRACT (EPOCH FROM CURRENT_TIMESTAMP::time) AS Em_segundos;
SELECT TO_CHAR((64223.338843 || 'second')::interval, 'HH24:MM:SS') AS tempo_total;

SELECT NOW() AS data_hora;

CREATE DATABASE subconsulta;